### ISSUE TITLE
NotAuthorizedException error

### ISSUE THREAD

**Issue by clever98** [drozhkov/aws-cpp-cognito-auth#3]
I'm getting "NotAuthorizedException Incorrect username or password" error with your example.
"cipClient.InitiateAuth( authRequest )" returns with success,
But "cipClient.RespondToAuthChallenge( challengeRequest )" returns with that error.
Is this sample still work for you?

**Comment by clever98** [comment]
Now I found out my problem. I used the UserPoolID with a region string.
Sorry for bothering you.

**Comment by drozhkov** [comment]
> Now I found out my problem. I used the UserPoolID with a region string.

good

> Sorry for bothering you.

no problem
